// <auto-generated />
namespace Trellendar.DataAccess.Local.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class LocationTextMarkers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LocationTextMarkers));
        
        string IMigrationMetadata.Id
        {
            get { return "201308152210327_LocationTextMarkers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
