// <auto-generated />
namespace Trellendar.DataAccess.Local.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BoardCalendarBondIntroduction1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BoardCalendarBondIntroduction1));
        
        string IMigrationMetadata.Id
        {
            get { return "201309012313439_BoardCalendarBondIntroduction1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
