//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 

using System.Xml.Serialization;

namespace Trellendar.Logic.TimeZones {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class supplementalData {
        
        private supplementalDataVersion versionField;
        
        private supplementalDataGeneration generationField;
        
        private supplementalDataWindowsZones windowsZonesField;
        
        /// <remarks/>
        public supplementalDataVersion version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public supplementalDataGeneration generation {
            get {
                return this.generationField;
            }
            set {
                this.generationField = value;
            }
        }
        
        /// <remarks/>
        public supplementalDataWindowsZones windowsZones {
            get {
                return this.windowsZonesField;
            }
            set {
                this.windowsZonesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class supplementalDataVersion {
        
        private string numberField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class supplementalDataGeneration {
        
        private string dateField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class supplementalDataWindowsZones {
        
        private supplementalDataWindowsZonesMapTimezones mapTimezonesField;
        
        /// <remarks/>
        public supplementalDataWindowsZonesMapTimezones mapTimezones {
            get {
                return this.mapTimezonesField;
            }
            set {
                this.mapTimezonesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class supplementalDataWindowsZonesMapTimezones {
        
        private supplementalDataWindowsZonesMapTimezonesMapZone[] mapZoneField;
        
        private string otherVersionField;
        
        private string typeVersionField;
        
        /// <remarks/>
        [XmlElement("mapZone")]
        public supplementalDataWindowsZonesMapTimezonesMapZone[] mapZone {
            get {
                return this.mapZoneField;
            }
            set {
                this.mapZoneField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string otherVersion {
            get {
                return this.otherVersionField;
            }
            set {
                this.otherVersionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string typeVersion {
            get {
                return this.typeVersionField;
            }
            set {
                this.typeVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class supplementalDataWindowsZonesMapTimezonesMapZone {
        
        private string otherField;
        
        private string territoryField;
        
        private string typeField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string other {
            get {
                return this.otherField;
            }
            set {
                this.otherField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string territory {
            get {
                return this.territoryField;
            }
            set {
                this.territoryField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
}
