// <auto-generated />
namespace Trellendar.DataAccess.Native.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ConstraintsAndLastSynchronizationTS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConstraintsAndLastSynchronizationTS));
        
        string IMigrationMetadata.Id
        {
            get { return "201307191930256_ConstraintsAndLastSynchronizationTS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
