//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trellendar.WebSite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trellendar.WebSite.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind.
        /// </summary>
        public static string BindAction {
            get {
                return ResourceManager.GetString("BindAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boards.
        /// </summary>
        public static string BoardsItem {
            get {
                return ResourceManager.GetString("BoardsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonds.
        /// </summary>
        public static string BondsItem {
            get {
                return ResourceManager.GetString("BondsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Bonds.
        /// </summary>
        public static string BondsPageTite {
            get {
                return ResourceManager.GetString("BondsPageTite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bonds have been saved successfully.
        /// </summary>
        public static string BondsSavedMessage {
            get {
                return ResourceManager.GetString("BondsSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendars.
        /// </summary>
        public static string CalendarsItem {
            get {
                return ResourceManager.GetString("CalendarsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        public static string ClickAction {
            get {
                return ResourceManager.GetString("ClickAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditAction {
            get {
                return ResourceManager.GetString("EditAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in with Google.
        /// </summary>
        public static string GoogleLogInAction {
            get {
                return ResourceManager.GetString("GoogleLogInAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOutAction {
            get {
                return ResourceManager.GetString("LogOutAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your profile.
        /// </summary>
        public static string ManageProfileAction {
            get {
                return ResourceManager.GetString("ManageProfileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveAction {
            get {
                return ResourceManager.GetString("SaveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to retrieve a token allowing Trellendar to read your Trello data:.
        /// </summary>
        public static string TrelloAuthorizationPrompt {
            get {
                return ResourceManager.GetString("TrelloAuthorizationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trello Log In.
        /// </summary>
        public static string TrelloLogInPageTitle {
            get {
                return ResourceManager.GetString("TrelloLogInPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please paste the token here and click &quot;submit&quot; button:.
        /// </summary>
        public static string TrelloTokenPrompt {
            get {
                return ResourceManager.GetString("TrelloTokenPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbind.
        /// </summary>
        public static string UnbindAction {
            get {
                return ResourceManager.GetString("UnbindAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occured.
        /// </summary>
        public static string UnknownErrorMessage {
            get {
                return ResourceManager.GetString("UnknownErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, {0}.
        /// </summary>
        public static string UserGreeting {
            get {
                return ResourceManager.GetString("UserGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Profile.
        /// </summary>
        public static string UserProfilePageTitle {
            get {
                return ResourceManager.GetString("UserProfilePageTitle", resourceCulture);
            }
        }
    }
}
